### ISSUE TITLE
Put Android app in the F-Droid marketplace

### ISSUE THREAD

**Issue by micahflee** [pockethub/PocketHub#156]
F-Droid is a free software alternative market for Android: http://f-droid.org/

It would be awesome to get the GitHub app in it, as well as in Google Play.

**Comment by SecUpwN** [comment]
Since conversations have been locked for me in #872 and #948, I will respond a last time on this here: I just added PocketHub to the [F-Droid Submission Queue](https://f-droid.org/forums/topic/pockethub/) so that the F-Droid developers can have a closer look at the PocketHub code and give a definite answer if adding it to F-Droid really is impossible as stated in https://github.com/pockethub/PocketHub/issues/872#issuecomment-166628476. Please do not answer here to avoid ticking off PocketHub developers, stay patient and monitor the ongoing discussion linked on the F-Droid forum. Thank me later when it is added.

**Comment by hzsweers** [comment]
It's locked because you keep harassing us to do it and hijacking other issues. You got the same answer there that you got here. We're not going to put credentials in VCS. Consider this your final warning, you need to take no for an answer.
