### ISSUE TITLE
Build Failing - Encryption key not generated.

### ISSUE THREAD

**Issue by babineaum** [pockethub/PocketHub#884]
I am not sure how to handle this error 

```0.01s$ openssl aes-256-cbc -K $encrypted_7e1c958561a2_key -iv $encrypted_7e1c958561a2_iv -in github.properties.enc -out github.properties -d```
```iv undefined```
```The command "openssl aes-256-cbc -K $encrypted_7e1c958561a2_key -iv $encrypted_7e1c958561a2_iv -in github.properties.enc -out github.properties -d" failed and exited with 1 during .```

there was a change added about 10 days ago and it seems to have taken the build out. If someone could put into the README how to handle this it would be really helpful. I think it has to do with this. http://docs.travis-ci.com/user/encrypting-files/

**Comment by larsgrefer** [comment]
The keys needed to decrypt the ```github.properties.enc``` file are set as two environment variables (```$encrypted_7e1c958561a2_key``` and ```$encrypted_7e1c958561a2_iv```) in the repository settings of travis-ci.

On forks and pull requests those secure variables aren't available, so the ```openssl``` command fails

**Comment by fadils** [comment]
@Meisolsson and @larsgrefer are already making a fix about this, and it's under review.
Sorry for this.

**Comment by froyomuffin** [comment]
Possibly silly questions:

Why not make the content of github.properties environment variables in travis? Then .travis.yml before_script can be changed to something like:
echo "GITHUB_CLIENT=$GITHUB_CLIENT" >> github.properties
echo "GITHUB_SECRET=$GITHUB_SECRET" >> github.properties
echo "GITHUB_CALLBACK=$GITHUB_CALLBACK" >> github.properties

Like this you can decouple the travis github.properties (github.properties.enc) from the code. It also makes it easier for people to set up their own travis ci.

Since the key and iv are secured in travis (I may be wrong here), securing the content of github.properties in travis would make the system negligibly less secure: in the event where travis is compromised, the underlying application client and secret can be easily had in either cases.

Please correct me if I'm not making sense. :)

**Comment by Meisolsson** [comment]
Sorry been gone for a while, the problem with environment variables is that they can't be used on fork builds. So we just have to remove them.

**Comment by larsgrefer** [comment]
@Meisolsson The encrypted ```github.properties.enc``` file can not be used on forks either, because the decryption keys are stored as environment variables. With #885 we will get multiple ways to set the 3 values (project gradle.properties, user gradle.properties, environment-variables, command-line options)

**Comment by froyomuffin** [comment]
Ah I see. :)

**Comment by larsgrefer** [comment]
@froyomuffin You are absolutley right.

We can use special environment variables which will be used directly by gradle:
> If the environment variable name looks like ```ORG_GRADLE_PROJECT_prop=somevalue```, then Gradle will set a ```prop``` property on your project object, with the value of ```somevalue```.

Using this we don't need the ```github.properties(.enc)``` file at all

**Comment by froyomuffin** [comment]
@larsgrefer @Meisolsson 
If the github.properties(.enc) file is dropped in favor of environment variables for gradle, we would still have the issue that we're having today with travis environment variables not being available for pull requests (I understand this is for security reasons?).

I just tried building (gradle clean build) and running unit tests (gradle test) and both seem to do fine without having the github values populated. Could we configure gradle and .travis.yml to simply builld without the github info (as it would be the case in PRs)?

**Comment by larsgrefer** [comment]
@froyomuffin My pull request intends to use the build-in property system of gradle. This allows multiple ways of setting properties:
1. gradle.properties file in the project directory
2. gradle.properties file in the users home directory (~/.gradle/gradle.properties)
3. Special named environment variables
4. Command line parameters
My pull request provides dummy values inside the project's gradle.properties in order to let the build proceed in every case. On your local machine these dummy values can be overridden from the gradle.properties in your home directory and on secure Travis builds (neither pull request nor forks) the values can be overridden by environment variables. (Unsecure Travis builds will use the dummy values instead)

**Comment by Meisolsson** [comment]
Well the value are already set in none are found and form what I have read there is no way to use environment variables on fork build on Travis

**Comment by larsgrefer** [comment]
@Meisolsson For security reasons environment variables are not available on pull requests and forks
> http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

At the moment we have the issue that travis fails when the environment variables are not available. This will be solved by #885
