### ISSUE TITLE
2fa - appears to be broken

### ISSUE THREAD

**Issue by andyrj** [pockethub/PocketHub#956]
Just tested app with 2fa enabled via Yubico Authenticator, my credentials work on github.com along with my 2fa codes.  However pockethub complains, "Please enter valid password".

If I disable 2fa on github temporarily then I can login fine and it all works, however I don't wish to disable 2fa just so I can use this mobile app. :(

Also verified that 2fa works with other mobile apps that integrate with github login (gitter) and it worked fine.

**Comment by hzsweers** [comment]
What version of the app are you running? Is it built from master or the play store?

**Comment by cburschka** [comment]
I am getting the same issue. My version is from the play store (1.9.0).

Both the password and the 2FA code are correctly verified, because I get different errors with the wrong ones: A wrong password will be rejected without a 2FA prompt; a wrong 2FA code will show the error "Unable to connect to github" instead of "Please enter valid login credentials").

I've been using this app with 2FA successfully as recently as May; I don't know when it stopped working.

**Comment by Meisolsson** [comment]
Since this is a play store issue it's irrelevant for now. The app has been taken down from the Play Store and is not supported. We will in the near future release a app which will fix these issues.
